// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.0
// source: service9001.proto

package proto9001

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestFor9001 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *RequestFor9001) Reset() {
	*x = RequestFor9001{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service9001_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestFor9001) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestFor9001) ProtoMessage() {}

func (x *RequestFor9001) ProtoReflect() protoreflect.Message {
	mi := &file_service9001_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestFor9001.ProtoReflect.Descriptor instead.
func (*RequestFor9001) Descriptor() ([]byte, []int) {
	return file_service9001_proto_rawDescGZIP(), []int{0}
}

func (x *RequestFor9001) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ResponseFor9001 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Class string `protobuf:"bytes,2,opt,name=Class,proto3" json:"Class,omitempty"`
	Roll  int64  `protobuf:"varint,3,opt,name=Roll,proto3" json:"Roll,omitempty"`
}

func (x *ResponseFor9001) Reset() {
	*x = ResponseFor9001{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service9001_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseFor9001) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseFor9001) ProtoMessage() {}

func (x *ResponseFor9001) ProtoReflect() protoreflect.Message {
	mi := &file_service9001_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseFor9001.ProtoReflect.Descriptor instead.
func (*ResponseFor9001) Descriptor() ([]byte, []int) {
	return file_service9001_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseFor9001) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResponseFor9001) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *ResponseFor9001) GetRoll() int64 {
	if x != nil {
		return x.Roll
	}
	return 0
}

var File_service9001_proto protoreflect.FileDescriptor

var file_service9001_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x39, 0x30, 0x30, 0x31, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x39, 0x30, 0x30, 0x31, 0x22, 0x24,
	0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x6f, 0x72, 0x39, 0x30, 0x30, 0x31,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x4f, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x46, 0x6f, 0x72, 0x39, 0x30, 0x30, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x52, 0x6f, 0x6c, 0x6c, 0x32, 0x53, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x39, 0x30, 0x30, 0x31, 0x12, 0x40, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x39, 0x30, 0x30, 0x31, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x6f, 0x72, 0x39, 0x30, 0x30, 0x31, 0x1a, 0x1a,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x39, 0x30, 0x30, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x46, 0x6f, 0x72, 0x39, 0x30, 0x30, 0x31, 0x42, 0x15, 0x5a, 0x13, 0x2e, 0x2f,
	0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x39, 0x30, 0x30,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service9001_proto_rawDescOnce sync.Once
	file_service9001_proto_rawDescData = file_service9001_proto_rawDesc
)

func file_service9001_proto_rawDescGZIP() []byte {
	file_service9001_proto_rawDescOnce.Do(func() {
		file_service9001_proto_rawDescData = protoimpl.X.CompressGZIP(file_service9001_proto_rawDescData)
	})
	return file_service9001_proto_rawDescData
}

var file_service9001_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service9001_proto_goTypes = []interface{}{
	(*RequestFor9001)(nil),  // 0: proto9001.RequestFor9001
	(*ResponseFor9001)(nil), // 1: proto9001.ResponseFor9001
}
var file_service9001_proto_depIdxs = []int32{
	0, // 0: proto9001.UserService9001.GetUser:input_type -> proto9001.RequestFor9001
	1, // 1: proto9001.UserService9001.GetUser:output_type -> proto9001.ResponseFor9001
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service9001_proto_init() }
func file_service9001_proto_init() {
	if File_service9001_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service9001_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestFor9001); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service9001_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseFor9001); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service9001_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service9001_proto_goTypes,
		DependencyIndexes: file_service9001_proto_depIdxs,
		MessageInfos:      file_service9001_proto_msgTypes,
	}.Build()
	File_service9001_proto = out.File
	file_service9001_proto_rawDesc = nil
	file_service9001_proto_goTypes = nil
	file_service9001_proto_depIdxs = nil
}
